version: 2
jobs:
  build: 
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: 3.6-alpine3.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout 
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }} 
      - run:
          command: |
            sudo pip install pipenv         
            pipenv install pytest
            pip install pytest
            pip install pygithub
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
            
      - run: 
          command: run python /home/ubunto/githubtest/github/tests/AllTests.py
          
      - store_test_results:
          path: test-results          
          
      - store_artifacts:
          path: test-reports
          destination: test-reports

